// Generated by Wrangler

import { D1Database, KVNamespace } from "@cloudflare/workers-types/experimental";

// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    sanctum_link: KVNamespace;
    MAILGUN_DOMAIN: string;
    MAILGUN_API_KEY: string;
    BACKEND_PRIVATE_KEY: string;
    sanctumdb: D1Database;
}
